typography_spectrum: 0.5304528975393623
color:
  brandStrength: 0.32734626019373536
  lightness: 0.8362136771902442
  saturation: 0.9952659097034484
  rhythmicContrast: 0.6689799160230905
  brandColors:
    - '#FFFFFF'
    - '#9AD2C9'
    - '#4C4845'
    - '#A4A1A0'
    - '#72716F'
layout_spectrum: 0.6822190526872873
author:
  name: Jurriaan
  email: jurriaanhes@gmail.com
name: bump it down the road
title: Random stuff I like to post
description: Food // Cooking // Gardening // Interior design // Etc
