author:
  name: Jurriaan
  email: jurriaanhes@gmail.com
title: Stuff I like to post
name: bump it down the road
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.9952659097034484
  brandStrength: 0.3273462601937354
  rhythmicContrast: 0.6689799160230905
  brandColors:
    - '#FFFFFF'
    - '#9AD2C9'
    - '#4C4845'
    - '#A4A1A0'
    - '#72716F'
  lightness: 0.8362136771902442
coverPrefs:
  filter: false
typography_spectrum: 0.5304528975393623
layout_spectrum: 0.8954469
navigation:
  - name: Instagram
    url: 'https://www.instagram.com/jurriaanhes/'
    type: external
analytics:
  twitter: ''
  facebook: ''
  google: UA-82875695-1
